function Hd = HzFDF
%0.5HZFDF Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
% Generated on: 25-Nov-2019 20:26:54

% FIR Window Highpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 5000;  % Sampling Frequency

N    = 7;        % Order
Fc   = 0.5;      % Cutoff Frequency
flag = 'scale';  % Sampling Flag

% Create the window vector for the design algorithm.
win = hamming(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'high', win, flag, 'h');
Hd = dfilt.dffir(b);

% [EOF]
